# base
project_name: countdown
model_name: ???
temperature: 1.0
iteration: 0
split: train

# directory
data_dir: checkpoints/${project_name}/${model_name}/gen/temp_${temperature}/iter_${iteration}
output_dir: checkpoints/${project_name}/${model_name}/data/temp_${temperature}/iter_${iteration}

# dataset
dataset:
  path: parquet
  data_dir: ${data_dir}
  split: train
