# base
project_name: code_repair
model_name: ???
temperature: 1.0
num_turns: 4
num_iters: 0
split: train

# directory
data_dir: checkpoints/${project_name}/${model_name}/gen/temp_${temperature}/turn_${num_turns}/iter_${num_iters}
output_dir: checkpoints/${project_name}/${model_name}/eval/temp_${temperature}/turn_${num_turns}/iter_${num_iters}

# dataset
dataset:
  path: parquet
  data_dir: ${data_dir}
  split: train
