# base
project_name: code_repair
model_name: ???
temperature: 1.0
num_turns: 4
num_iters: 0
split: train
start: 0
num_examples: 100
seed: 0
max_prompt_length: 2048
max_response_length: 16384

# directory
data_dir: /home/seungyong/Projects/verl/data/${project_name}/rl
model_dir: /home/seungyong/Projects/verl/checkpoints/${project_name}/${model_name}/huggingface
output_dir: /home/seungyong/Projects/verl/checkpoints/${project_name}/${model_name}/gen/temp_${temperature}/turn_${num_turns}/iter_${num_iters}

# dataset
dataset:
  path: parquet
  data_dir: ${data_dir}
  data_files: ${split}.parquet
  split: train

# llm
llm:
  model: ${model_dir}
  tensor_parallel_size: 1
  seed: ${seed}
  gpu_memory_utilization: 0.9

# sampling params
sampling_params:
  temperature: ${temperature}
  top_p: 1.0
  top_k: -1
